### ISSUE TITLE
Client disconnects after 2 requests

### ISSUE THREAD

**Issue by jacobay43** [getnamo/MachineLearningRemote-Unreal#11]
I appreciate the work on this project.
I am trying to create a program that allows you to input your name and then it generates an image watermark with that name on the server end and returns the watermarked image path to the client which then imports it as a texture file from disk. It works fine, but after 2 requests, the client disconnects by itself and although the server still generates the images for the requests, it just does not return the images via the on-input result event anymore. The blueprint:
![image](https://user-images.githubusercontent.com/54321724/162569450-1ff00376-af7e-49bf-a115-e65ed4bf1efe.png)
So I would like to know if there is a way to increase the number of requests or if perhaps I throttle the blueprint.

**Comment by getnamo** [comment]
Plugin/Engine version? What's the size of the data you're transporting?

**Comment by jacobay43** [comment]
Unreal engine version: 4.27
MachineLearningRemote plugin version: 0.3.0
SocketIO plugin version: 1.8.0

The data being sent is text while the data being received on_gt_callback is a string containing the path to the generated image so I would say a few bytes. The watermark ed image/texture loading is done solely on the ue4 client side using the import file from disk function and the size of the image is around 1.3mb

**Comment by jacobay43** [comment]
After upgrading to version 0.7.0 on Unreal Engine 5.0, the problem was fixed. Thank your

**Comment by getnamo** [comment]
Great 👍
