### ISSUE TITLE
Error when packaging for Windows (UE5)

### ISSUE THREAD

**Issue by jacobay43** [getnamo/MachineLearningRemote-Unreal#13]
Hello. 
I get the following traceback in the output log when attempting to package a project with this plugin for windows.

- `UATHelper: Packaging (Windows): ********** BUILD COMMAND STARTED **********
- UATHelper: Packaging (Windows): Running: E:\Unreal Projects\UE_5.0\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.exe SMyProject Win64 Development -Project="E:\SMyProject 5.0\SMyProject.uproject"  "E:\SMyProject 5.0\SMyProject.uproject" -NoUBTMakefiles  -remoteini="E:\SMyProject 5.0" -skipdeploy -Manifest="E:\SMyProject 5.0\Intermediate\Build\Manifest.xml" -NoHotReload -log="C:\Users\Usuario\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+Projects+UE_5.0\UBT-SMyProject-Win64-Development.txt"
- UATHelper: Packaging (Windows): Log file: C:\Users\Usuario\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+Projects+UE_5.0\UBT-SMyProject-Win64-Development.txt
- UATHelper: Packaging (Windows): Writing manifest to E:\SMyProject 5.0\Intermediate\Build\Manifest.xml
- UATHelper: Packaging (Windows): Building SMyProject...
- UATHelper: Packaging (Windows): Using Visual Studio 2019 14.29.30143 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
- UATHelper: Packaging (Windows): [Adaptive Build] Excluded from SMyProject unity file: SMyProject.cpp, TestClass.cpp
- UATHelper: Packaging (Windows): Determining max actions to execute in parallel (8 physical cores, 8 logical cores)
- UATHelper: Packaging (Windows):   Executing up to 8 processes, one per physical core
- UATHelper: Packaging (Windows): Building 2 actions with 2 processes...
- UATHelper: Packaging (Windows): [1/2] Link SMyProject.exe
`UATHelper: Packaging (Windows): Module.MachineLearningRemote.cpp.obj : error LNK2005: ya se defini� "struct FLogCategoryMLBaseLog MLBaseLog" (?MLBaseLog@@3UFLogCategoryMLBaseLog@@A) en Module.MachineLearningBase.cpp.obj
`
`UATHelper: Packaging (Windows):    Creando biblioteca E:\SMyProject 5.0\Binaries\Win64\SMyProject.lib y objeto E:\SMyProject 5.0\Binaries\Win64\SMyProject.exp`
 `UATHelper: Packaging (Windows): E:\SMyProject 5.0\Binaries\Win64\SMyProject.exe : fatal error LNK1169: se encontraron uno o m�s s�mbolos definidos simult�neamente`
- UATHelper: Packaging (Windows): Took 5.7030024s to run UnrealBuildTool.exe, ExitCode=6
- UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\<USER>\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+Projects+UE_5.0\UBT-SMyProject-Win64-Development.txt)
- UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 7s
- UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
- UATHelper: Packaging (Windows): Updating environment variables set by a Turnkey sub-process
- UATHelper: Packaging (Windows): The system cannot find the path specified.
- UATHelper: Packaging (Windows): The system cannot find the path specified.

`

This roughly translates to Fatal error: One or more symbols simultaneously defined
struct FLogCategoryMLBaseLog MLBaseLog seems to be what is causing the issue.

**Comment by jacobay43** [comment]
In english

```
UATHelper: Packaging (Windows): [27/28] Link MyProject.exe
UATHelper: Packaging (Windows): Module.MachineLearningRemote.cpp.obj : error LNK2005: "struct FLogCategoryMLBaseLog MLBaseLog" (?MLBaseLog@@3UFLogCategoryMLBaseLog@@A) already defined in Module.MachineLearningBase.cpp.obj
UATHelper: Packaging (Windows):    Creating library C:\Users\LENOVO\Documents\Unreal Projects\MyProject\Binaries\Win64\MyProject.lib and object C:\Users\LENOVO\Documents\Unreal Projects\MyProject\Binaries\Win64\MyProject.exp
UATHelper: Packaging (Windows): C:\Users\LENOVO\Documents\Unreal Projects\MyProject\Binaries\Win64\MyProject.exe : fatal error LNK1169: one or more multiply defined symbols found
UATHelper: Packaging (Windows): Took 1536.889484s to run UnrealBuildTool.exe, ExitCode=6
```

**Comment by getnamo** [comment]
Re-pull master with latest fix https://github.com/getnamo/MachineLearningRemote-Unreal/commit/ab2a37e3a1c64ba16bc900fd9ed686f9707dd048 and let me know if that fixes it

**Comment by jacobay43** [comment]
The issue is fixed. Thank you
